# Generated by Django 5.2.17 on 2026-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
